# Generated by Django 6.0.7 on 2026-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('abuseipdb', 'AbuseIPDB'), ('macvendors', 'MAC Vendors'), ('virustotal', 'VirusTotal')], max_length=32, unique=True)),
                ('api_key_encrypted', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('quota_limit', models.IntegerField(default=0, help_text='Daily quota limit (0 = unlimited)')),
                ('quota_used', models.IntegerField(default=0)),
                ('quota_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'intelligence_api_keys',
            },
        ),
        migrations.CreateModel(
            name='IntelligenceIpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('abuse_confidence_score', models.IntegerField(default=0)),
                ('country_code', models.CharField(blank=True, default='', max_length=4)),
                ('country_name', models.CharField(blank=True, default='', max_length=128)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('total_reports', models.IntegerField(default=0)),
                ('num_distinct_users', models.IntegerField(default=0)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('reports', models.JSONField(blank=True, default=list)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP Report',
                'verbose_name_plural': 'IP Reports',
                'db_table': 'intelligence_ip_reports',
                'indexes': [models.Index(fields=['ip_address', '-queried_at'], name='intelligenc_ip_addr_4b322e_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceMacLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('is_private', models.BooleanField(default=False)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MAC Lookup',
                'verbose_name_plural': 'MAC Lookups',
                'db_table': 'intelligence_mac_lookups',
                'indexes': [models.Index(fields=['mac_address', '-queried_at'], name='intelligenc_mac_add_63a58e_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ip_enrich', 'IP Enrichment'), ('domain_enrich', 'Domain Enrichment'), ('url_scan', 'URL Scan'), ('hash_scan', 'File Hash Scan'), ('soar_playbook', 'SOAR Playbook')], max_length=32)),
                ('target', models.CharField(help_text='IP, domain, URL or hash', max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scan Job',
                'verbose_name_plural': 'Scan Jobs',
                'db_table': 'intelligence_scan_jobs',
                'indexes': [models.Index(fields=['status', 'created_at'], name='intelligenc_status_784406_idx'), models.Index(fields=['job_type'], name='intelligenc_job_typ_665088_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceVtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(db_index=True, max_length=1024)),
                ('indicator_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash')], max_length=16)),
                ('malicious', models.IntegerField(default=0)),
                ('suspicious', models.IntegerField(default=0)),
                ('harmless', models.IntegerField(default=0)),
                ('undetected', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0)),
                ('last_analysis_stats', models.JSONField(blank=True, default=dict)),
                ('reputation_score', models.IntegerField(default=0, help_text='-100 to 100')),
                ('verbose_msg', models.TextField(blank=True, default='')),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VirusTotal Report',
                'verbose_name_plural': 'VirusTotal Reports',
                'db_table': 'intelligence_vt_reports',
                'indexes': [models.Index(fields=['indicator', '-queried_at'], name='intelligenc_indicat_1b7624_idx'), models.Index(fields=['indicator_type', 'malicious'], name='intelligenc_indicat_b2e632_idx')],
            },
        ),
    ]
