# Generated by Django 6.0.5 on 2026-05-08 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlpPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='high', max_length=16)),
                ('scan_paths', models.JSONField(blank=True, default=list)),
                ('monitored_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dlp_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DlpScanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_agent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('host_name', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('files_scanned', models.IntegerField(default=0)),
                ('files_flagged', models.IntegerField(default=0)),
                ('incidents_created', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('error', 'Error')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dlp_scan_summaries',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DlpIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('remote_agent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('host_name', models.CharField(blank=True, default='', max_length=255)),
                ('policy_code', models.CharField(db_index=True, max_length=64)),
                ('rule_name', models.CharField(max_length=255)),
                ('classification', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='high', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('acknowledged', 'Acknowledged')], db_index=True, default='open', max_length=24)),
                ('file_name', models.CharField(max_length=512)),
                ('file_path', models.TextField()),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('cloud', 'Cloud Storage'), ('web', 'Web Upload'), ('usb', 'USB/Removable'), ('network', 'Network Share'), ('documents', 'Documents Folder'), ('filesystem', 'Filesystem')], default='filesystem', max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'dlp_incidents',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['severity', 'status'], name='dlp_inciden_severit_44ce75_idx'), models.Index(fields=['classification', 'status'], name='dlp_inciden_classif_fec8de_idx'), models.Index(fields=['remote_agent_id', 'detected_at'], name='dlp_inciden_remote__b8a05e_idx'), models.Index(fields=['file_path'], name='dlp_inciden_file_pa_31dbee_idx')],
            },
        ),
        migrations.CreateModel(
            name='DlpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pattern', models.TextField(help_text='Keyword or regex pattern to match')),
                ('match_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regex'), ('metadata', 'Metadata')], default='keyword', max_length=16)),
                ('classification', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='high', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='DLP.dlppolicy')),
            ],
            options={
                'db_table': 'dlp_rules',
                'indexes': [models.Index(fields=['policy', 'enabled'], name='dlp_rules_policy__e0dedd_idx')],
            },
        ),
    ]
