# Generated by Django 5.2.3 on 2025-09-22 00:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("acronimo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionMonitoreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervalo_segundos",
                    models.IntegerField(
                        default=60, help_text="Intervalo de monitoreo en segundos"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=False,
                        help_text="Si el servicio de monitoreo está activo",
                    ),
                ),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuración de Monitoreo",
                "verbose_name_plural": "Configuraciones de Monitoreo",
            },
        ),
        migrations.CreateModel(
            name="Involucrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=200)),
                ("apellidos", models.CharField(max_length=200)),
                ("usuario", models.CharField(max_length=200)),
                ("ip", models.GenericIPAddressField()),
                ("mac", models.CharField(max_length=17)),
                ("tipo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Medida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=200)),
                ("apellidos", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefono_particular", models.CharField(max_length=20)),
                ("telefono_corp", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "host",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP del servicio para monitoreo",
                        null=True,
                    ),
                ),
                (
                    "monitorear",
                    models.BooleanField(
                        default=False, help_text="Activar monitoreo de este servicio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("nombre_incidente", models.CharField(max_length=200)),
                (
                    "codigo_incidente",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                ("descripcion", models.TextField()),
                (
                    "evidencia",
                    models.FileField(blank=True, null=True, upload_to="evidencias/"),
                ),
                (
                    "estado_solucion",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("abierto", "Abierto"),
                            ("investigacion", "Investigación"),
                            ("mitigacion", "Mitigación"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="nuevo",
                        max_length=13,
                    ),
                ),
                (
                    "notificado_osri",
                    models.CharField(
                        choices=[("si", "Sí"), ("no", "No")], default="no", max_length=2
                    ),
                ),
                ("areas", models.ManyToManyField(to="EVENT_M.area")),
            ],
        ),
        migrations.CreateModel(
            name="InvolucradoIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "incidente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.incidente",
                    ),
                ),
                (
                    "involucrado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.involucrado",
                    ),
                ),
                (
                    "medida_impuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EVENT_M.medida"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_informante", models.CharField(max_length=200)),
                ("email_informante", models.EmailField(max_length=254)),
                ("descripcion", models.TextField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_solucion",
                    models.CharField(
                        choices=[
                            ("Nuevo", "Nuevo"),
                            ("Atendido", "Atendido"),
                            ("Rechazado", "Rechazado"),
                        ],
                        default="nuevo",
                        max_length=13,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EVENT_M.area"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidente",
            name="reporte",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="EVENT_M.reporte"
            ),
        ),
        migrations.CreateModel(
            name="MedidaIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_cumplimiento", models.DateField()),
                ("estado_cumplimiento", models.BooleanField(default=False)),
                ("observaciones", models.TextField()),
                (
                    "incidente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.incidente",
                    ),
                ),
                (
                    "medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EVENT_M.medida"
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.responsable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin",
                to="EVENT_M.responsable",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="cuadro_centro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuadro_centro",
                to="EVENT_M.responsable",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="rsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsi",
                to="EVENT_M.responsable",
            ),
        ),
        migrations.AddField(
            model_name="incidente",
            name="servicios",
            field=models.ManyToManyField(to="EVENT_M.servicio"),
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "nivel_peligrosidad",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.categoria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidente",
            name="subcategorias",
            field=models.ManyToManyField(to="EVENT_M.subcategoria"),
        ),
        migrations.CreateModel(
            name="MonitoreoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "latencia",
                    models.FloatField(
                        blank=True, help_text="Latencia en milisegundos", null=True
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=False, help_text="True si el servicio está activo"
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si falla el ping",
                        null=True,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.servicio",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["servicio", "-timestamp"],
                        name="EVENT_M_mon_servici_8ff22f_idx",
                    )
                ],
            },
        ),
    ]
