# Generated by Django 6.0.3 on 2026-03-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='tipo',
            field=models.CharField(choices=[('Cuadro Centro', 'Cuadro Centro'), ('RSI', 'RSI'), ('Admin', 'Administrador')], default='Cuadro Centro', max_length=200),
        ),
    ]
