# Generated by Django 5.2.3 on 2026-03-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0002_alter_responsable_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estado_solucion',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Atendido', 'Atendido'), ('Rechazado', 'Rechazado')], default='Nuevo', max_length=13),
        ),
    ]
