# Generated by Django 5.2.3 on 2026-05-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0003_alter_reporte_estado_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
