# Generated by Django 6.0.5 on 2026-05-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0004_reporte_fecha_atencion_reporte_fecha_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
