# Generated by Django 6.0.5 on 2026-05-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0005_incidente_fecha_atencion_incidente_fecha_solucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='reporte',
        ),
        migrations.AddField(
            model_name='incidente',
            name='reportes',
            field=models.ManyToManyField(related_name='incidentes', to='EVENT_M.reporte'),
        ),
    ]
