# Generated by Django 6.0.5 on 2026-05-06 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0006_remove_incidente_reporte_incidente_reportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionTopologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fisica', 'Conexion Fisica'), ('logica', 'Conexion Logica'), ('wireless', 'Conexion Inalambrica'), ('vpn', 'VPN/Tunel'), ('virtual', 'Virtual (VM/Container)')], default='fisica', max_length=20)),
                ('medio', models.CharField(blank=True, choices=[('fibra', 'Fibra Optica'), ('cobre', 'Cobre (Ethernet)'), ('wireless', 'Inalambrico'), ('virtual', 'Virtual'), ('otro', 'Otro')], max_length=20, null=True)),
                ('ancho_banda', models.CharField(blank=True, help_text='Ej: 1Gbps, 10Gbps', max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['origen', 'destino'],
            },
        ),
        migrations.CreateModel(
            name='PuertoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puerto', models.IntegerField(help_text='Numero de puerto fisico')),
                ('etiqueta', models.CharField(blank=True, help_text='Etiqueta del puerto (ej: Gi0/1)', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('vlan_asignada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('velocidad', models.CharField(choices=[('10m', '10 Mbps'), ('100m', '100 Mbps'), ('1g', '1 Gbps'), ('10g', '10 Gbps'), ('40g', '40 Gbps'), ('100g', '100 Gbps')], default='1g', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reservado', 'Reservado'), ('error', 'Error')], default='activo', max_length=20)),
                ('duplex', models.CharField(choices=[('full', 'Full Duplex'), ('half', 'Half Duplex'), ('auto', 'Auto')], default='auto', max_length=10)),
            ],
            options={
                'ordering': ['dispositivo', 'numero_puerto'],
            },
        ),
        migrations.CreateModel(
            name='ServicioIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, help_text='Direccion MAC', max_length=17, null=True)),
                ('monitorear', models.BooleanField(default=False, help_text='Monitorear esta IP especifica')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('reservado', 'Reservado'), ('monitoreo', 'Solo Monitoreo')], default='activo', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el servicio esta activo o dado de baja'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key si aplica', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='coordenadas_logicas_x',
            field=models.IntegerField(default=0, help_text='Posicion X para topologia logica'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='coordenadas_logicas_y',
            field=models.IntegerField(default=0, help_text='Posicion Y para topologia logica'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='coordenadas_x',
            field=models.IntegerField(default=0, help_text='Posicion X para topologia fisica'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='coordenadas_y',
            field=models.IntegerField(default=0, help_text='Posicion Y para topologia fisica'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dispositivo_tipo',
            field=models.CharField(blank=True, choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('ups', 'UPS'), ('storage', 'Storage/NAS')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='edificio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado_monitoreo',
            field=models.BooleanField(default=True, help_text='Estado actual del monitoreo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='firmware',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='intervalo_segundos',
            field=models.IntegerField(default=60, help_text='Intervalo de monitoreo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ip_range_end',
            field=models.GenericIPAddressField(blank=True, help_text='IP fin del rango', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ip_range_start',
            field=models.GenericIPAddressField(blank=True, help_text='IP inicio del rango', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nivel_red',
            field=models.IntegerField(default=0, help_text='Nivel en la jerarquia de red (0=core, 1=distribucion, 2=acceso)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='num_puertos',
            field=models.IntegerField(blank=True, choices=[(4, '4 puertos'), (8, '8 puertos'), (10, '10 puertos'), (16, '16 puertos'), (24, '24 puertos'), (28, '28 puertos'), (48, '48 puertos'), (56, '56 puertos')], null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='piso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('proxmox', 'Proxmox VE'), ('vmware', 'VMware ESXi'), ('hyper_v', 'Microsoft Hyper-V'), ('kubernetes', 'Kubernetes'), ('docker', 'Docker'), ('otro', 'Otro')], help_text='Plataforma de virtualizacion', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='posicion_rack',
            field=models.IntegerField(blank=True, help_text='U en el rack', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='protocolo_monitoreo',
            field=models.CharField(choices=[('icmp', 'Ping ICMP'), ('tcp', 'TCP Port'), ('http', 'HTTP/HTTPS'), ('snmp', 'SNMP'), ('api', 'API Check')], default='icmp', help_text='Protocolo de monitoreo', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='puerto_monitoreo',
            field=models.IntegerField(default=80, help_text='Puerto para monitoreo TCP/HTTP'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='puerto_servicio',
            field=models.IntegerField(blank=True, help_text='Puerto del servicio', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='rack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EVENT_M.responsable'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicio_padre',
            field=models.ForeignKey(blank=True, help_text='Servicio padre (cluster, segmento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subservicios', to='EVENT_M.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicios_hijos',
            field=models.ManyToManyField(blank=True, related_name='servicios_padres', to='EVENT_M.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='subnet_mask',
            field=models.CharField(blank=True, help_text='Mascara CIDR (ej: /24)', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('host', 'Host/Servidor'), ('vlan', 'VLAN'), ('segmento', 'Segmento de Red'), ('dispositivo_red', 'Dispositivo de Red'), ('cluster', 'Cluster Virtualización (Proxmox/VMware)'), ('servicio_externo', 'Servicio Externo/SaaS')], default='host', max_length=30),
        ),
        migrations.AddField(
            model_name='servicio',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Rack, posicion, ubicacion fisica', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='url_servicio',
            field=models.URLField(blank=True, help_text='URL del servicio externo', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='vlan_id',
            field=models.IntegerField(blank=True, help_text='Tag VLAN (1-4094)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='host',
            field=models.GenericIPAddressField(blank=True, help_text='IP principal del servicio', null=True),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo'], name='EVENT_M_ser_tipo_1dbffc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['activo'], name='EVENT_M_ser_activo_d83b57_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['monitorear'], name='EVENT_M_ser_monitor_959fa5_idx'),
        ),
        migrations.AddField(
            model_name='conexiontopologica',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='EVENT_M.servicio'),
        ),
        migrations.AddField(
            model_name='conexiontopologica',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='EVENT_M.servicio'),
        ),
        migrations.AddField(
            model_name='puertodispositivo',
            name='conectado_a_puerto',
            field=models.ForeignKey(blank=True, help_text='Puerto remoto conectado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conectado_desde', to='EVENT_M.puertodispositivo'),
        ),
        migrations.AddField(
            model_name='puertodispositivo',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='EVENT_M.servicio'),
        ),
        migrations.AddField(
            model_name='conexiontopologica',
            name='puerto_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexion_destino', to='EVENT_M.puertodispositivo'),
        ),
        migrations.AddField(
            model_name='conexiontopologica',
            name='puerto_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conexion_origen', to='EVENT_M.puertodispositivo'),
        ),
        migrations.AddField(
            model_name='servicioip',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='EVENT_M.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='puertodispositivo',
            unique_together={('dispositivo', 'numero_puerto')},
        ),
        migrations.AlterUniqueTogether(
            name='conexiontopologica',
            unique_together={('origen', 'destino', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='servicioip',
            unique_together={('servicio', 'ip_address')},
        ),
    ]
