# Generated by Django 6.0.5 on 2026-05-06 05:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0007_conexiontopologica_puertodispositivo_servicioip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Ultima vez detectado activo por monitoreo', null=True),
        ),
        migrations.AddField(
            model_name='servicioip',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Ultima vez que estuvo activo/visible', null=True),
        ),
        migrations.CreateModel(
            name='Subred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('network', models.GenericIPAddressField(help_text='Direccion de red (ej: 10.10.0.0)')),
                ('subnet_mask', models.CharField(help_text='Mascara CIDR o completa (ej: /24 o 255.255.255.0)', max_length=18)),
                ('gateway', models.GenericIPAddressField(blank=True, help_text='Gateway de la subred', null=True)),
                ('tipo', models.CharField(choices=[('interna', 'Red Interna'), ('dmz', 'DMZ'), ('gestion', 'Gestion'), ('usuarios', 'Usuarios'), ('servidores', 'Servidores'), ('vpn', 'VPN'), ('iot', 'IoT'), ('guest', 'Guest/Visitantes'), ('backup', 'Backup/Storage'), ('otro', 'Otro')], default='interna', max_length=20)),
                ('vlan_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('dns_primario', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_secundario', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp_activo', models.BooleanField(default=False, help_text='Si DHCP esta habilitado en esta subred')),
                ('dhcp_rango_inicio', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp_rango_fin', models.GenericIPAddressField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(blank=True, help_text='Servicio asociado a esta subred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subredes', to='EVENT_M.servicio')),
            ],
            options={
                'ordering': ['network'],
            },
        ),
        migrations.AddField(
            model_name='servicioip',
            name='subred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='EVENT_M.subred'),
        ),
    ]
