# Generated by Django 6.0.5 on 2026-05-06 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0008_servicio_ultima_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioip',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='EVENT_M.servicio'),
        ),
    ]
