# Generated by Django 6.0.5 on 2026-05-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0009_alter_servicioip_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioip',
            name='subred',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='dispositivo_tipo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='ip_range_end',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='ip_range_start',
        ),
        migrations.AddField(
            model_name='servicio',
            name='dhcp_activo',
            field=models.BooleanField(default=False, help_text='DHCP habilitado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dhcp_rango_fin',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dhcp_rango_inicio',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dns_primario',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dns_secundario',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, help_text='Gateway de la subred', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='network',
            field=models.GenericIPAddressField(blank=True, help_text='Direccion de red (ej: 10.10.0.0)', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='red_tipo',
            field=models.CharField(blank=True, choices=[('interna', 'Red Interna'), ('dmz', 'DMZ'), ('gestion', 'Gestion'), ('usuarios', 'Usuarios'), ('servidores', 'Servidores'), ('vpn', 'VPN'), ('iot', 'IoT'), ('guest', 'Guest/Visitantes'), ('backup', 'Backup/Storage'), ('otro', 'Otro')], help_text='Tipo de red (solo para subred/segmento/red)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subnet_mask',
            field=models.CharField(blank=True, help_text='Mascara CIDR (ej: /24 o 255.255.255.0)', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('host', 'Host/Servidor'), ('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('ups', 'UPS'), ('storage', 'Storage/NAS'), ('vlan', 'VLAN'), ('segmento', 'Segmento de Red'), ('subred', 'Subred'), ('red', 'Red'), ('cluster', 'Cluster Virtualización'), ('plataforma', 'Plataforma'), ('servicio_externo', 'Servicio Externo/SaaS')], default='host', max_length=30),
        ),
        migrations.DeleteModel(
            name='Subred',
        ),
    ]
