# Generated by Django 6.0.5 on 2026-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0010_remove_subred_add_red_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='intervalo_segundos',
            field=models.IntegerField(blank=True, default=60, help_text='Intervalo de monitoreo'),
        ),
    ]
