# Generated by Django 6.0.5 on 2026-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_M', '0011_fix_intervalo_segundos_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(blank=True, default=True, help_text='Si el servicio esta activo o dado de baja'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='dhcp_activo',
            field=models.BooleanField(blank=True, default=False, help_text='DHCP habilitado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='monitorear',
            field=models.BooleanField(blank=True, default=False, help_text='Activar monitoreo de este servicio'),
        ),
    ]
