# Generated by Django 6.0.3 on 2026-03-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ingest', '0003_saved_visualizations_dashboards'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saveddashboard',
            new_name='ids_ingest__owner_i_a4b660_idx',
            old_name='ids_ingest__owner_i_8e286c_idx',
        ),
        migrations.RenameIndex(
            model_name='saveddashboard',
            new_name='ids_ingest__space_600a3f_idx',
            old_name='ids_ingest__space_i_c3a4c6_idx',
        ),
        migrations.RenameIndex(
            model_name='savedvisualization',
            new_name='ids_ingest__owner_i_8220c0_idx',
            old_name='ids_ingest__owner_i_09f502_idx',
        ),
        migrations.RenameIndex(
            model_name='savedvisualization',
            new_name='ids_ingest__space_c95374_idx',
            old_name='ids_ingest__space_i_5b44e3_idx',
        ),
    ]
