# Generated by Django 5.2.3 on 2025-09-22 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDSIngestConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ids_type",
                    models.CharField(
                        choices=[("snort", "Snort"), ("suricata", "Suricata")],
                        max_length=10,
                    ),
                ),
                ("log_path", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("retention_days", models.IntegerField(default=30)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "last_position",
                    models.BigIntegerField(
                        default=0, help_text="Última posición leída en el archivo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración IDS/IPS",
                "verbose_name_plural": "Configuraciones IDS/IPS",
            },
        ),
        migrations.CreateModel(
            name="IDSStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ids_type",
                    models.CharField(
                        choices=[("snort", "Snort"), ("suricata", "Suricata")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("total_events", models.IntegerField(default=0)),
                ("critical_events", models.IntegerField(default=0)),
                ("high_events", models.IntegerField(default=0)),
                ("medium_events", models.IntegerField(default=0)),
                ("low_events", models.IntegerField(default=0)),
                ("unique_src_ips", models.IntegerField(default=0)),
                ("unique_dst_ips", models.IntegerField(default=0)),
                ("top_protocols", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Estadística IDS/IPS",
                "verbose_name_plural": "Estadísticas IDS/IPS",
                "ordering": ["-date"],
                "unique_together": {("ids_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="SnortLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("severity", models.CharField(db_index=True, max_length=20)),
                ("priority", models.IntegerField(default=0)),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dst_ip", models.GenericIPAddressField(db_index=True)),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(db_index=True, max_length=10)),
                ("message", models.TextField()),
                ("gid", models.IntegerField(default=0)),
                ("sid", models.IntegerField(default=0)),
                ("rev", models.IntegerField(default=0)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw", models.TextField()),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ttl",
                    models.IntegerField(
                        blank=True, help_text="Time To Live", null=True
                    ),
                ),
                (
                    "tos",
                    models.CharField(
                        blank=True,
                        help_text="Type of Service",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "packet_id",
                    models.IntegerField(blank=True, help_text="Packet ID", null=True),
                ),
                (
                    "ip_len",
                    models.IntegerField(
                        blank=True, help_text="IP Header Length", null=True
                    ),
                ),
                (
                    "dgm_len",
                    models.IntegerField(
                        blank=True, help_text="Datagram Length", null=True
                    ),
                ),
                (
                    "flags",
                    models.CharField(
                        blank=True, help_text="TCP Flags", max_length=20, null=True
                    ),
                ),
                (
                    "seq",
                    models.CharField(
                        blank=True,
                        help_text="Sequence Number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ack",
                    models.CharField(
                        blank=True,
                        help_text="Acknowledgment Number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "win",
                    models.CharField(
                        blank=True, help_text="Window Size", max_length=20, null=True
                    ),
                ),
                (
                    "tcp_len",
                    models.IntegerField(
                        blank=True, help_text="TCP Header Length", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Snort",
                "verbose_name_plural": "Logs Snort",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="ids_ingest__timesta_8eb6fd_idx",
                    ),
                    models.Index(
                        fields=["src_ip", "dst_ip"],
                        name="ids_ingest__src_ip_96cec8_idx",
                    ),
                    models.Index(
                        fields=["protocol", "severity"],
                        name="ids_ingest__protoco_02d9aa_idx",
                    ),
                    models.Index(
                        fields=["sid", "gid"], name="ids_ingest__sid_680996_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuricataEveAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dest_ip", models.GenericIPAddressField(db_index=True)),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dest_port", models.IntegerField(blank=True, null=True)),
                ("proto", models.CharField(db_index=True, max_length=10)),
                ("signature_id", models.IntegerField(db_index=True)),
                ("signature_rev", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("action", models.CharField(default="alert", max_length=20)),
                ("severity", models.IntegerField(default=1)),
                ("message", models.TextField()),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alerta Suricata EVE",
                "verbose_name_plural": "Alertas Suricata EVE",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="ids_ingest__timesta_b58d15_idx",
                    ),
                    models.Index(
                        fields=["src_ip", "dest_ip"],
                        name="ids_ingest__src_ip_9d81e6_idx",
                    ),
                    models.Index(
                        fields=["signature_id", "severity"],
                        name="ids_ingest__signatu_de46e8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuricataFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dest_ip", models.GenericIPAddressField(db_index=True)),
                ("src_port", models.IntegerField()),
                ("dest_port", models.IntegerField()),
                ("proto", models.CharField(db_index=True, max_length=10)),
                ("app_proto", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                ("pkts_toserver", models.BigIntegerField(default=0)),
                ("pkts_toclient", models.BigIntegerField(default=0)),
                ("bytes_toserver", models.BigIntegerField(default=0)),
                ("bytes_toclient", models.BigIntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("age", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Flujo Suricata",
                "verbose_name_plural": "Flujos Suricata",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "proto"],
                        name="ids_ingest__timesta_793cd4_idx",
                    ),
                    models.Index(
                        fields=["src_ip", "dest_ip"],
                        name="ids_ingest__src_ip_b2f311_idx",
                    ),
                    models.Index(
                        fields=["app_proto", "state"],
                        name="ids_ingest__app_pro_568ed2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuricataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("severity", models.CharField(db_index=True, max_length=20)),
                ("priority", models.IntegerField(default=0)),
                ("src_ip", models.GenericIPAddressField(db_index=True)),
                ("dst_ip", models.GenericIPAddressField(db_index=True)),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(db_index=True, max_length=10)),
                ("message", models.TextField()),
                ("gid", models.IntegerField(default=0)),
                ("sid", models.IntegerField(default=0)),
                ("rev", models.IntegerField(default=0)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw", models.TextField()),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log Suricata",
                "verbose_name_plural": "Logs Suricata",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="ids_ingest__timesta_c82b1a_idx",
                    ),
                    models.Index(
                        fields=["src_ip", "dst_ip"],
                        name="ids_ingest__src_ip_586820_idx",
                    ),
                    models.Index(
                        fields=["protocol", "severity"],
                        name="ids_ingest__protoco_89c3a0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuricataStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("uptime", models.IntegerField(default=0)),
                ("total_packets", models.BigIntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("packets_per_second", models.FloatField(default=0.0)),
                ("bytes_per_second", models.FloatField(default=0.0)),
                ("total_flows", models.BigIntegerField(default=0)),
                ("total_alerts", models.BigIntegerField(default=0)),
                ("total_drops", models.BigIntegerField(default=0)),
                ("memory_usage", models.FloatField(default=0.0)),
                ("cpu_usage", models.FloatField(default=0.0)),
                ("rules_loaded", models.IntegerField(default=0)),
                ("rules_failed", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Estadística Suricata",
                "verbose_name_plural": "Estadísticas Suricata",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="ids_ingest__timesta_9e147a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuricataSystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("NOTICE", "Notice"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("component", models.CharField(blank=True, max_length=50, null=True)),
                ("message", models.TextField()),
                ("raw_line", models.TextField()),
                (
                    "log_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único para evitar duplicidad",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log Sistema Suricata",
                "verbose_name_plural": "Logs Sistema Suricata",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "level"],
                        name="ids_ingest__timesta_0764f1_idx",
                    ),
                    models.Index(
                        fields=["component", "level"],
                        name="ids_ingest__compone_77adba_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IDSAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ids_type",
                    models.CharField(
                        choices=[("snort", "Snort"), ("suricata", "Suricata")],
                        max_length=10,
                    ),
                ),
                ("log_id", models.BigIntegerField(help_text="ID del log original")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("src_ip", models.GenericIPAddressField()),
                ("dst_ip", models.GenericIPAddressField()),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta IDS/IPS",
                "verbose_name_plural": "Alertas IDS/IPS",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["severity", "acknowledged"],
                        name="ids_ingest__severit_f15788_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="ids_ingest__timesta_8e585e_idx",
                    ),
                ],
            },
        ),
    ]
