# Generated by Django 5.2.3 on 2025-09-22 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_async_processing",
                    models.BooleanField(
                        default=True, help_text="Habilitar procesamiento asíncrono"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Máximo número de reintentos"
                    ),
                ),
                (
                    "cleanup_days",
                    models.IntegerField(
                        default=30, help_text="Días para mantener notificaciones"
                    ),
                ),
                (
                    "email_batch_size",
                    models.IntegerField(
                        default=50, help_text="Tamaño del lote para emails masivos"
                    ),
                ),
                (
                    "email_rate_limit",
                    models.IntegerField(
                        default=100, help_text="Límite de emails por hora"
                    ),
                ),
                (
                    "sms_provider",
                    models.CharField(
                        blank=True, help_text="Proveedor de SMS", max_length=50
                    ),
                ),
                (
                    "sms_api_key",
                    models.CharField(
                        blank=True, help_text="API Key para SMS", max_length=255
                    ),
                ),
                (
                    "sms_rate_limit",
                    models.IntegerField(default=20, help_text="Límite de SMS por hora"),
                ),
                (
                    "slack_webhook_url",
                    models.URLField(blank=True, help_text="URL del webhook de Slack"),
                ),
                (
                    "slack_default_channel",
                    models.CharField(
                        default="#alerts", help_text="Canal por defecto", max_length=100
                    ),
                ),
                (
                    "teams_webhook_url",
                    models.URLField(blank=True, help_text="URL del webhook de Teams"),
                ),
                (
                    "webhook_timeout",
                    models.IntegerField(
                        default=30, help_text="Timeout para webhooks (segundos)"
                    ),
                ),
                (
                    "webhook_retries",
                    models.IntegerField(
                        default=2, help_text="Reintentos para webhooks"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False, help_text="Habilitar notificaciones push"
                    ),
                ),
                (
                    "push_vapid_key",
                    models.TextField(
                        blank=True, help_text="Clave VAPID para push notifications"
                    ),
                ),
                (
                    "auto_cleanup",
                    models.BooleanField(
                        default=True, help_text="Limpieza automática habilitada"
                    ),
                ),
                (
                    "cleanup_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Cada hora"),
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Notificaciones",
                "verbose_name_plural": "Configuraciones de Notificaciones",
            },
        ),
        migrations.CreateModel(
            name="AnalysisAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "virustotal_api_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "abuseipdb_api_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "macvendors_api_key",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_api_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de APIs de Análisis",
                "verbose_name_plural": "Configuraciones de APIs de Análisis",
            },
        ),
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la configuración",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(help_text="Servidor SMTP", max_length=255),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, help_text="Puerto SMTP"),
                ),
                ("use_tls", models.BooleanField(default=True, help_text="Usar TLS")),
                ("use_ssl", models.BooleanField(default=False, help_text="Usar SSL")),
                (
                    "username",
                    models.CharField(
                        help_text="Usuario del servidor SMTP", max_length=255
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Contraseña del servidor SMTP", max_length=255
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(help_text="Email remitente", max_length=254),
                ),
                (
                    "from_name",
                    models.CharField(
                        default="VANT-SIEM",
                        help_text="Nombre del remitente",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Configuración activa"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Correo",
                "verbose_name_plural": "Configuraciones de Correo",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATE_REQUEST", "Solicitud de Creación de Usuario"),
                            ("USER_APPROVED", "Usuario Aprobado"),
                            ("USER_REJECTED", "Usuario Rechazado"),
                            ("INCIDENT_CREATED", "Incidente Creado"),
                            ("INCIDENT_UPDATED", "Incidente Actualizado"),
                            ("REPORT_CREATED", "Reporte Creado"),
                            ("REPORT_UPDATED", "Reporte Actualizado"),
                            ("SECURITY_EVENT", "Evento de Seguridad"),
                            ("SYSTEM_ERROR", "Error del Sistema"),
                            ("BACKUP_COMPLETED", "Respaldo Completado"),
                            ("BACKUP_FAILED", "Respaldo Fallido"),
                            ("MAINTENANCE_SCHEDULED", "Mantenimiento Programado"),
                            ("LOGIN_FAILED", "Intento de Login Fallido"),
                            ("PERMISSION_CHANGED", "Permisos Modificados"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Fallido"),
                            ("BOUNCED", "Rebotado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si falló el envío"
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Correo",
                "verbose_name_plural": "Logs de Correos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATE_REQUEST", "Solicitud de Creación de Usuario"),
                            (
                                "USER_APPROVAL_REQUEST",
                                "Solicitud de Aprobación de Usuario",
                            ),
                            ("CRITICAL_OPERATION", "Operación Crítica"),
                            ("SYSTEM_ALERT", "Alerta del Sistema"),
                            ("DATA_CHANGE", "Cambio de Datos"),
                            ("SECURITY_EVENT", "Evento de Seguridad"),
                            ("BACKUP_COMPLETE", "Respaldo Completado"),
                            ("MAINTENANCE", "Mantenimiento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                            ("WEBHOOK", "Webhook"),
                            ("BROWSER_PUSH", "Notificación Push del Navegador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Configuración específica del canal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de Notificación",
                "verbose_name_plural": "Canales de Notificación",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_creation_notifications", models.BooleanField(default=True)),
                ("user_approval_notifications", models.BooleanField(default=True)),
                ("critical_operation_notifications", models.BooleanField(default=True)),
                ("system_alert_notifications", models.BooleanField(default=True)),
                ("data_change_notifications", models.BooleanField(default=False)),
                ("security_event_notifications", models.BooleanField(default=True)),
                ("backup_notifications", models.BooleanField(default=False)),
                ("maintenance_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("browser_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Notificación",
                "verbose_name_plural": "Preferencias de Notificaciones",
            },
        ),
        migrations.CreateModel(
            name="OllamaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ollama_url",
                    models.URLField(
                        default="http://localhost:11434",
                        help_text="URL del servidor Ollama",
                    ),
                ),
                (
                    "ollama_model",
                    models.CharField(
                        default="llama3.2",
                        help_text="Modelo de IA a utilizar",
                        max_length=100,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=2000, help_text="Máximo número de tokens en respuestas"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.3, help_text="Temperatura para generación (0.1-1.0)"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(
                        default=30, help_text="Timeout en segundos para llamadas"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Servicio de IA habilitado"
                    ),
                ),
                (
                    "can_read_snort_logs",
                    models.BooleanField(
                        default=True, help_text="Puede leer logs de Snort"
                    ),
                ),
                (
                    "can_read_suricata_logs",
                    models.BooleanField(
                        default=True, help_text="Puede leer logs de Suricata"
                    ),
                ),
                (
                    "can_read_incidents",
                    models.BooleanField(
                        default=True, help_text="Puede leer incidentes"
                    ),
                ),
                (
                    "can_read_reports",
                    models.BooleanField(default=True, help_text="Puede leer reportes"),
                ),
                (
                    "can_read_users",
                    models.BooleanField(
                        default=False, help_text="Puede leer datos de usuarios"
                    ),
                ),
                (
                    "can_read_system_logs",
                    models.BooleanField(
                        default=False, help_text="Puede leer logs del sistema"
                    ),
                ),
                (
                    "auto_generate_reports",
                    models.BooleanField(
                        default=False,
                        help_text="Generar reportes automáticamente en alertas",
                    ),
                ),
                (
                    "auto_send_emails",
                    models.BooleanField(
                        default=False, help_text="Enviar emails automáticamente"
                    ),
                ),
                (
                    "auto_create_incidents",
                    models.BooleanField(
                        default=False, help_text="Crear incidentes automáticamente"
                    ),
                ),
                (
                    "alert_threshold_critical",
                    models.IntegerField(
                        default=10, help_text="Umbral para alertas críticas"
                    ),
                ),
                (
                    "alert_threshold_high",
                    models.IntegerField(
                        default=50, help_text="Umbral para alertas altas"
                    ),
                ),
                (
                    "auto_report_interval_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Intervalo para reportes automáticos (horas)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Ollama",
                "verbose_name_plural": "Configuraciones de Ollama",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=128)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Usuario",
                "verbose_name_plural": "Solicitudes de Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATE_REQUEST", "Solicitud de Creación de Usuario"),
                            ("USER_APPROVED", "Usuario Aprobado"),
                            ("USER_REJECTED", "Usuario Rechazado"),
                            ("INCIDENT_CREATED", "Incidente Creado"),
                            ("INCIDENT_UPDATED", "Incidente Actualizado"),
                            ("REPORT_CREATED", "Reporte Creado"),
                            ("REPORT_UPDATED", "Reporte Actualizado"),
                            ("SECURITY_EVENT", "Evento de Seguridad"),
                            ("SYSTEM_ERROR", "Error del Sistema"),
                            ("BACKUP_COMPLETED", "Respaldo Completado"),
                            ("BACKUP_FAILED", "Respaldo Fallido"),
                            ("MAINTENANCE_SCHEDULED", "Mantenimiento Programado"),
                            ("LOGIN_FAILED", "Intento de Login Fallido"),
                            ("PERMISSION_CHANGED", "Permisos Modificados"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Alerta habilitada"),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, help_text="Plantilla del asunto", max_length=255
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        blank=True, help_text="Plantilla del cuerpo del correo"
                    ),
                ),
                (
                    "send_immediately",
                    models.BooleanField(
                        default=True, help_text="Enviar inmediatamente"
                    ),
                ),
                (
                    "send_daily_summary",
                    models.BooleanField(
                        default=False, help_text="Incluir en resumen diario"
                    ),
                ),
                (
                    "send_weekly_summary",
                    models.BooleanField(
                        default=False, help_text="Incluir en resumen semanal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta por Correo",
                "verbose_name_plural": "Alertas por Correo",
                "ordering": ["user__username", "alert_type"],
                "unique_together": {("user", "alert_type")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("SENT", "Enviada"),
                            ("FAILED", "Fallida"),
                            ("RETRY", "Reintentar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("channel_type", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_time",
                    models.FloatField(
                        blank=True, help_text="Tiempo de entrega en segundos", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VANT_SIEM.notificationchannel",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VANT_SIEM.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Notificación",
                "verbose_name_plural": "Logs de Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "channel_type"],
                        name="VANT_SIEM_n_status_6b3da9_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="VANT_SIEM_n_sent_at_582555_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("SENT", "Enviada"),
                            ("FAILED", "Fallida"),
                            ("RETRY", "Reintentar"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Prioridad (1-5, 5 es más alta)"
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VANT_SIEM.notificationchannel",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VANT_SIEM.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación en Cola",
                "verbose_name_plural": "Notificaciones en Cola",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="VANT_SIEM_n_status_d4a422_idx",
                    ),
                    models.Index(
                        fields=["scheduled_at"], name="VANT_SIEM_n_schedul_7a0095_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre único de la plantilla",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                            ("WEBHOOK", "Webhook"),
                            ("BROWSER_PUSH", "Notificación Push del Navegador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATE_REQUEST", "Solicitud de Creación de Usuario"),
                            (
                                "USER_APPROVAL_REQUEST",
                                "Solicitud de Aprobación de Usuario",
                            ),
                            ("CRITICAL_OPERATION", "Operación Crítica"),
                            ("SYSTEM_ALERT", "Alerta del Sistema"),
                            ("DATA_CHANGE", "Cambio de Datos"),
                            ("SECURITY_EVENT", "Evento de Seguridad"),
                            ("BACKUP_COMPLETE", "Respaldo Completado"),
                            ("MAINTENANCE", "Mantenimiento"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Plantilla del asunto (solo para email)",
                        max_length=255,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(help_text="Plantilla del cuerpo del mensaje"),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=dict,
                        help_text="Variables disponibles para esta plantilla",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Notificación",
                "verbose_name_plural": "Plantillas de Notificación",
                "unique_together": {("template_type", "event_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("CAN_LOGIN", "Puede Autenticarse"),
                            ("VIEW_REPORTES", "Ver Reportes"),
                            ("CREATE_REPORTES", "Crear Reportes"),
                            ("EDIT_REPORTES", "Editar Reportes"),
                            ("DELETE_REPORTES", "Eliminar Reportes"),
                            ("VIEW_INCIDENTES", "Ver Incidentes"),
                            ("CREATE_INCIDENTES", "Crear Incidentes"),
                            ("EDIT_INCIDENTES", "Editar Incidentes"),
                            ("DELETE_INCIDENTES", "Eliminar Incidentes"),
                            ("VIEW_USERS", "Ver Usuarios"),
                            ("CREATE_USERS", "Crear Usuarios"),
                            ("EDIT_USERS", "Editar Usuarios"),
                            ("DELETE_USERS", "Eliminar Usuarios"),
                            ("VIEW_LOGS", "Ver Logs"),
                            ("VIEW_NOTIFICATIONS", "Ver Notificaciones"),
                            ("MANAGE_PERMISSIONS", "Gestionar Permisos"),
                            ("VIEW_DASHBOARD", "Ver Dashboard"),
                            ("EXPORT_DATA", "Exportar Datos"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Usuario",
                "verbose_name_plural": "Permisos de Usuarios",
                "unique_together": {("user", "permission_type")},
            },
        ),
    ]
