# Generated by Django 5.2.3 on 2025-09-26 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VANT_SIEM', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseIPDBAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Dirección IP analizada')),
                ('status_code', models.IntegerField(help_text='Código de estado HTTP de la respuesta')),
                ('result', models.JSONField(default=dict, help_text='Resultado completo de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuseipdb_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis AbuseIPDB',
                'verbose_name_plural': 'Análisis AbuseIPDB',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='VANT_SIEM_a_ip_addr_65bb6a_idx'), models.Index(fields=['requested_by', 'created_at'], name='VANT_SIEM_a_request_adadc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MacVendorsAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='Dirección MAC analizada', max_length=17)),
                ('vendor', models.CharField(blank=True, help_text='Fabricante identificado', max_length=255)),
                ('status_code', models.IntegerField(help_text='Código de estado HTTP de la respuesta')),
                ('result', models.JSONField(default=dict, help_text='Resultado completo de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macvendors_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis MacVendors',
                'verbose_name_plural': 'Análisis MacVendors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mac_address', 'created_at'], name='VANT_SIEM_m_mac_add_31d283_idx'), models.Index(fields=['vendor', 'created_at'], name='VANT_SIEM_m_vendor_5f5a07_idx'), models.Index(fields=['requested_by', 'created_at'], name='VANT_SIEM_m_request_b1fded_idx')],
            },
        ),
        migrations.CreateModel(
            name='VTAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(db_index=True, help_text='Indicador analizado', max_length=2048)),
                ('indicator_type', models.CharField(choices=[('domain', 'Dominio'), ('url', 'URL'), ('file', 'Archivo'), ('ip', 'Dirección IP')], db_index=True, max_length=20)),
                ('status_code', models.IntegerField(help_text='Código de estado HTTP de la respuesta')),
                ('result', models.JSONField(default=dict, help_text='Resultado completo de la API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vt_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis VirusTotal',
                'verbose_name_plural': 'Análisis VirusTotal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['indicator_type', 'created_at'], name='VANT_SIEM_v_indicat_af19e5_idx'), models.Index(fields=['requested_by', 'created_at'], name='VANT_SIEM_v_request_157cd2_idx')],
            },
        ),
    ]
