# Generated by Django 5.2.3 on 2025-10-04 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VANT_SIEM", "0002_abuseipdbanalysisrecord_macvendorsanalysisrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre único del agente", max_length=100, unique=True
                    ),
                ),
                (
                    "machine_name",
                    models.CharField(
                        help_text="Nombre de la máquina donde está instalado",
                        max_length=255,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("DEBIAN", "Debian/Ubuntu"),
                            ("CENTOS", "CentOS/RHEL"),
                            ("OTHER", "Otro"),
                        ],
                        help_text="Tipo de sistema operativo",
                        max_length=20,
                    ),
                ),
                (
                    "server_ip",
                    models.GenericIPAddressField(help_text="IP del servidor VANT-SIEM"),
                ),
                (
                    "server_port",
                    models.IntegerField(
                        default=8000, help_text="Puerto del servidor VANT-SIEM"
                    ),
                ),
                (
                    "agent_port",
                    models.IntegerField(
                        help_text="Puerto único para este agente", unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("PENDING", "Pendiente"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True, help_text="Último latido recibido", null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Versión del agente", max_length=50
                    ),
                ),
                (
                    "system_info",
                    models.JSONField(
                        default=dict, help_text="Información del sistema del agente"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Agente habilitado"),
                ),
                (
                    "auto_start",
                    models.BooleanField(
                        default=True, help_text="Iniciar automáticamente al arranque"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente",
                "verbose_name_plural": "Agentes",
                "ordering": ["-created_at"],
            },
        ),
    ]
