# Generated by Django 5.2.5 on 2025-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VANT_SIEM", "0003_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="config_version",
            field=models.IntegerField(
                default=1, help_text="Versión de configuración actual"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="connection_quality",
            field=models.FloatField(default=0.0, help_text="Calidad de conexión (0-1)"),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_config_update",
            field=models.DateTimeField(
                blank=True, help_text="Última actualización de configuración", null=True
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="last_connection_error",
            field=models.TextField(blank=True, help_text="Último error de conexión"),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_alerts_sent",
            field=models.IntegerField(default=0, help_text="Total de alertas enviadas"),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_heartbeats",
            field=models.IntegerField(
                default=0, help_text="Total de heartbeats enviados"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_tasks_executed",
            field=models.IntegerField(
                default=0, help_text="Total de tareas ejecutadas"
            ),
        ),
    ]
