# Generated by Django 5.2.3 on 2025-10-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VANT_SIEM", "0004_agent_config_version_agent_connection_quality_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agent",
        ),
    ]
