# Generated by Django 6.0.3 on 2026-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VANT_SIEM', '0005_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la configuración', max_length=100, unique=True)),
                ('servidor', models.CharField(help_text='Dirección del servidor LDAP (ej: ldap://servidor.dominio.com)', max_length=255)),
                ('puerto', models.IntegerField(default=389, help_text='Puerto del servidor LDAP')),
                ('use_ssl', models.BooleanField(default=False, help_text='Usar SSL/TLS')),
                ('use_starttls', models.BooleanField(default=False, help_text='Usar StartTLS')),
                ('cert_path', models.CharField(blank=True, help_text='Ruta al certificado CA (opcional)', max_length=500, null=True)),
                ('bind_dn', models.CharField(blank=True, help_text='DN del usuario para bind (ej: cn=admin,dc=ejemplo,dc=com)', max_length=500, null=True)),
                ('bind_password', models.CharField(blank=True, help_text='Contraseña del usuario bind', max_length=255, null=True)),
                ('user_search_base', models.CharField(help_text='Base de búsqueda de usuarios (ej: ou=users,dc=ejemplo,dc=com)', max_length=500)),
                ('user_search_filter', models.CharField(default='(uid={username})', help_text='Filtro de búsqueda de usuarios', max_length=500)),
                ('group_search_base', models.CharField(blank=True, help_text='Base de búsqueda de grupos', max_length=500, null=True)),
                ('group_search_filter', models.CharField(default='(member={user_dn})', help_text='Filtro de búsqueda de grupos', max_length=500)),
                ('username_attr', models.CharField(default='uid', help_text='Atributo que contiene el nombre de usuario', max_length=100)),
                ('first_name_attr', models.CharField(default='givenName', help_text='Atributo para nombre', max_length=100)),
                ('last_name_attr', models.CharField(default='sn', help_text='Atributo para apellido', max_length=100)),
                ('email_attr', models.CharField(default='mail', help_text='Atributo para email', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Habilitar autenticación LDAP')),
                ('is_default', models.BooleanField(default=False, help_text='Usar como método de autenticación por defecto')),
                ('auto_create_user', models.BooleanField(default=True, help_text='Crear usuario automáticamente si no existe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración LDAP',
                'verbose_name_plural': 'Configuraciones LDAP',
                'ordering': ['-is_default', 'nombre'],
            },
        ),
    ]
