# Generated by Django 6.0.5 on 2026-05-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VANT_SIEM', '0006_ldapconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OllamaConfig',
        ),
    ]
