# Generated by Django 5.2.5 on 2026-04-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VANT_SIEM", "0006_ldapconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkChangeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("site_created", "Site Created"), ("vlan_created", "VLAN Created"), ("subnet_created", "Subnet Created"), ("ip_created", "IP Created")], max_length=40)),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Network Change Event",
                "verbose_name_plural": "Network Change Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Network Site",
                "verbose_name_plural": "Network Sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkVLAN",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vlan_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("vrf", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vlans", to="VANT_SIEM.networksite")),
            ],
            options={
                "verbose_name": "Network VLAN",
                "verbose_name_plural": "Network VLANs",
                "ordering": ["site__name", "vlan_id"],
                "unique_together": {("site", "vlan_id")},
            },
        ),
        migrations.CreateModel(
            name="NetworkSubnet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("cidr", models.CharField(max_length=64, unique=True)),
                ("gateway_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dhcp_enabled", models.BooleanField(default=False)),
                ("dhcp_range_start", models.GenericIPAddressField(blank=True, null=True)),
                ("dhcp_range_end", models.GenericIPAddressField(blank=True, null=True)),
                ("dns_servers", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("planning", "Planning"), ("active", "Active"), ("reserved", "Reserved"), ("deprecated", "Deprecated")], default="active", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subnets", to="VANT_SIEM.networksite")),
                ("vlan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subnets", to="VANT_SIEM.networkvlan")),
            ],
            options={
                "verbose_name": "Network Subnet",
                "verbose_name_plural": "Network Subnets",
                "ordering": ["site__name", "cidr"],
            },
        ),
        migrations.CreateModel(
            name="NetworkIPAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField()),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("dns_name", models.CharField(blank=True, max_length=255)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("device_role", models.CharField(blank=True, max_length=120)),
                ("assigned_to", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("assigned", "Assigned"), ("reserved", "Reserved"), ("available", "Available"), ("conflict", "Conflict"), ("quarantine", "Quarantine")], default="assigned", max_length=20)),
                ("source", models.CharField(blank=True, help_text="Origen del dato: agente, manual, importacion", max_length=120)),
                ("description", models.TextField(blank=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("subnet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ip_addresses", to="VANT_SIEM.networksubnet")),
            ],
            options={
                "verbose_name": "Network IP Address",
                "verbose_name_plural": "Network IP Addresses",
                "ordering": ["subnet__cidr", "ip_address"],
                "unique_together": {("subnet", "ip_address")},
            },
        ),
    ]
