# Generated by Django 6.0.5 on 2026-05-08 02:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlpPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique policy code (e.g. aegis-local-shield)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable policy name', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scan_paths', models.JSONField(blank=True, default=list, help_text='Paths to scan on agents')),
                ('monitored_extensions', models.JSONField(blank=True, default=list, help_text='File extensions to scan (e.g. .docx, .pdf)')),
                ('max_file_size_mb', models.IntegerField(default=25, help_text='Max file size in MB to scan')),
                ('max_scan_seconds', models.IntegerField(default=20, help_text='Max scan duration per agent cycle')),
                ('target_os', models.CharField(blank=True, default='', help_text='Target OS: windows, linux, or empty for all', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DLP Policy',
                'verbose_name_plural': 'DLP Policies',
                'db_table': 'assets_dlp_policies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DlpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Rule name (e.g. 'Clasificado', 'Confidential')", max_length=255)),
                ('classification', models.SlugField(help_text='Classification tag applied on match', max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('match_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regular Expression'), ('metadata', 'Metadata')], default='keyword', max_length=16)),
                ('pattern', models.TextField(help_text='Keyword or regex pattern to match')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ASSETS.dlppolicy')),
            ],
            options={
                'verbose_name': 'DLP Rule',
                'verbose_name_plural': 'DLP Rules',
                'db_table': 'assets_dlp_rules',
                'ordering': ['policy', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DlpThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 dedup key', max_length=128, unique=True)),
                ('agent_id', models.UUIDField(db_index=True, help_text='Agent that reported this threat')),
                ('agent_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('policy_code', models.SlugField(blank=True, default='', max_length=64)),
                ('rule_name', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.SlugField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=16)),
                ('file_name', models.CharField(blank=True, default='', max_length=512)),
                ('file_path', models.TextField(blank=True, default='')),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('actor', models.CharField(blank=True, default='', help_text='File owner / user', max_length=255)),
                ('channel', models.CharField(choices=[('filesystem', 'Filesystem'), ('downloads', 'Downloads'), ('desktop', 'Desktop'), ('documents', 'Documents'), ('removable', 'Removable Media'), ('network', 'Network Share'), ('email', 'Email'), ('clipboard', 'Clipboard'), ('usb', 'USB')], default='filesystem', max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_published', models.BooleanField(default=False, help_text='Whether the DLP event was published to the service bus')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DLP Threat',
                'verbose_name_plural': 'DLP Threats',
                'db_table': 'assets_dlp_threats',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['severity'], name='assets_dlp__severit_cc06d9_idx'), models.Index(fields=['classification'], name='assets_dlp__classif_f63e51_idx'), models.Index(fields=['agent_id', 'detected_at'], name='assets_dlp__agent_i_daf9d7_idx')],
            },
        ),
    ]
