"""
Django settings for CORE project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^(*y6l84+o!c#060jy^i!i$nf47o$c#aukx4)1&1=e7$b8l7)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','192.168.137.1','vantsc.duckdns.org','172.23.48.1','host.docker.internal','192.168.1.12','192.168.137.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'VANT_SIEM.apps.VantSiemConfig',
    'opensearch_service.apps.OpenSearchServiceConfig',
    'EVENT_M',
    'opensearch_ui.apps.OpenSearchUiConfig',
    'IRIS',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'VANT_SIEM.middleware.LoggingMiddleware',
]

ROOT_URLCONF = 'CORE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "VANT_SIEM/templates",
            BASE_DIR / "collector/templates",
            BASE_DIR / "EVENT_M/templates",
            BASE_DIR / "opensearch_ui/templates",
            BASE_DIR / "IRIS/templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CORE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vant_test1',           
        'USER': 'postgres', 
        'PASSWORD': 'postgres',   
        'HOST': 'localhost',           
        'PORT': '5432',               
    },
    'opensearch': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('OS_DB_NAME', 'vant_opensearch'),
        'USER': os.getenv('OS_DB_USER', 'postgres'),
        'PASSWORD': os.getenv('OS_DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('OS_DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('OS_DB_PORT', '5432'),
    },
}

DATABASE_ROUTERS = [
    "opensearch_service.db_router.OpenSearchRouter",
]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'VANT_SIEM' / 'assets',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_URL = '/siem/dashboard/login/'
LOGIN_REDIRECT_URL = '/siem/dashboard/' 
LOGOUT_REDIRECT_URL = '/siem/login/'
