# Generated by Django 5.2.5 on 2026-05-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcommand',
            name='command_type',
            field=models.CharField(choices=[('update_inventory', 'Update Inventory'), ('restart_agent', 'Restart Agent'), ('stop_agent', 'Stop Agent'), ('update_agent', 'Update Agent'), ('run_script', 'Run Script'), ('collect_logs', 'Collect Logs'), ('push_config', 'Push Configuration'), ('custom', 'Custom')], max_length=32),
        ),
    ]
