# Generated by Django 6.0.5 on 2026-05-11 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY', '0002_add_push_config_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcommand',
            name='command_type',
            field=models.CharField(choices=[('update_inventory', 'Update Inventory'), ('restart_agent', 'Restart Agent'), ('stop_agent', 'Stop Agent'), ('update_agent', 'Update Agent'), ('run_script', 'Run Script'), ('collect_logs', 'Collect Logs'), ('push_config', 'Push Configuration'), ('start_screen_share', 'Start Screen Sharing'), ('stop_screen_share', 'Stop Screen Sharing'), ('custom', 'Custom')], max_length=32),
        ),
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='INVENTORY.agent')),
            ],
            options={
                'db_table': 'screen_captures',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['agent', '-captured_at'], name='screen_capt_agent_i_a198f6_idx')],
            },
        ),
    ]
