# Generated by Django 5.2.3 on 2026-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_migrate_legacy_vant_siem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcommand',
            name='command',
            field=models.CharField(choices=[('stop', 'Stop'), ('restart', 'Restart'), ('activate', 'Activate')], max_length=20),
        ),
    ]
