# Generated by Django 5.2.3 on 2026-03-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_agentcommand_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='AegisDlpPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(default='high', max_length=20)),
                ('scan_paths', models.JSONField(blank=True, default=list)),
                ('monitored_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politica Aegis DLP',
                'verbose_name_plural': 'Politicas Aegis DLP',
            },
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='last_dlp_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='last_inventory_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdevice',
            name='latest_inventory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AegisDlpRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('classification', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.CharField(default='high', max_length=20)),
                ('match_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regex'), ('metadata', 'Metadata')], default='keyword', max_length=20)),
                ('pattern', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='inventory.aegisdlppolicy')),
            ],
            options={
                'verbose_name': 'Regla Aegis DLP',
                'verbose_name_plural': 'Reglas Aegis DLP',
            },
        ),
        migrations.CreateModel(
            name='AegisDlpIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.CharField(default='high', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='open', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlp_incidents', to='inventory.agentdevice')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='inventory.aegisdlppolicy')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='inventory.aegisdlprule')),
            ],
            options={
                'verbose_name': 'Incidente Aegis DLP',
                'verbose_name_plural': 'Incidentes Aegis DLP',
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentTimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('usb', 'USB'), ('user', 'User'), ('system', 'System'), ('dlp', 'DLP'), ('file', 'File')], default='system', max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('observed_at', models.DateTimeField()),
                ('source_service', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='inventory.agentdevice')),
            ],
            options={
                'verbose_name': 'Evento de linea de tiempo',
                'verbose_name_plural': 'Eventos de linea de tiempo',
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentHardwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('bios', 'BIOS'), ('system', 'System'), ('cpu', 'CPU'), ('board', 'Board'), ('memory', 'Memory'), ('disk', 'Disk'), ('network', 'Network'), ('usb', 'USB'), ('other', 'Other')], max_length=20)),
                ('fingerprint', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_components', to='inventory.agentdevice')),
            ],
            options={
                'verbose_name': 'Componente de hardware',
                'verbose_name_plural': 'Componentes de hardware',
                'unique_together': {('agent', 'component_type', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='AgentNetworkIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255)),
                ('interface_name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=64)),
                ('address_type', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('mac', 'MAC')], default='ipv4', max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_identities', to='inventory.agentdevice')),
            ],
            options={
                'verbose_name': 'Identidad de red',
                'verbose_name_plural': 'Identidades de red',
                'unique_together': {('agent', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='AgentSoftwareRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_present', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_records', to='inventory.agentdevice')),
            ],
            options={
                'verbose_name': 'Software observado',
                'verbose_name_plural': 'Software observado',
                'unique_together': {('agent', 'fingerprint')},
            },
        ),
    ]
