# Generated by Django 6.0.7 on 2026-07-26 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('machine_name', models.CharField(blank=True, default='', max_length=255)),
                ('os_type', models.CharField(choices=[('windows_10', 'Windows 10'), ('windows_11', 'Windows 11'), ('windows_server_2019', 'Windows Server 2019'), ('windows_server_2022', 'Windows Server 2022'), ('windows_server_2025', 'Windows Server 2025'), ('ubuntu_22_04', 'Ubuntu 22.04'), ('ubuntu_24_04', 'Ubuntu 24.04'), ('debian_12', 'Debian 12'), ('rhel_8', 'RHEL 8'), ('rhel_9', 'RHEL 9'), ('centos_9', 'CentOS Stream 9'), ('macos_14', 'macOS 14'), ('macos_15', 'macOS 15'), ('other_linux', 'Other Linux'), ('other', 'Other')], default='other', max_length=64)),
                ('os_version', models.CharField(blank=True, default='', max_length=128)),
                ('os_arch', models.CharField(default='x86_64', max_length=16)),
                ('agent_version', models.CharField(default='1.0.0', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pending', 'Pending Registration'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=16)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'inventory_agents',
                'indexes': [models.Index(fields=['hostname', 'status'], name='inventory_a_hostnam_329dbd_idx'), models.Index(fields=['os_type'], name='inventory_a_os_type_fd489f_idx'), models.Index(fields=['ip_address'], name='inventory_a_ip_addr_62d7a3_idx'), models.Index(fields=['status', 'last_heartbeat'], name='inventory_a_status_91d861_idx')],
            },
        ),
        migrations.CreateModel(
            name='HardwareInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('cpu_threads', models.IntegerField(default=0)),
                ('cpu_speed_ghz', models.FloatField(default=0)),
                ('ram_total_gb', models.FloatField(default=0)),
                ('ram_slots_used', models.IntegerField(default=0)),
                ('ram_slots_total', models.IntegerField(default=0)),
                ('motherboard_model', models.CharField(blank=True, default='', max_length=255)),
                ('motherboard_manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('bios_version', models.CharField(blank=True, default='', max_length=128)),
                ('gpu_models', models.JSONField(blank=True, default=list)),
                ('disks', models.JSONField(blank=True, default=list)),
                ('network_interfaces', models.JSONField(blank=True, default=list)),
                ('serial_number', models.CharField(blank=True, default='', max_length=128)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='inventory_app.agent')),
            ],
            options={
                'db_table': 'inventory_hardware',
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('update_inventory', 'Update Inventory'), ('restart_agent', 'Restart Agent'), ('stop_agent', 'Stop Agent'), ('update_agent', 'Update Agent'), ('run_script', 'Run Script'), ('collect_logs', 'Collect Logs'), ('collect_processes', 'Collect Processes & Ports'), ('push_config', 'Push Configuration'), ('start_screen_share', 'Start Screen Sharing'), ('stop_screen_share', 'Stop Screen Sharing'), ('list_services', 'List System Services'), ('list_apt_updates', 'Check APT Updates'), ('custom', 'Custom')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received by Agent'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='inventory_app.agent')),
            ],
            options={
                'db_table': 'inventory_commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='inventory_c_agent_i_810d72_idx'), models.Index(fields=['status', 'created_at'], name='inventory_c_status_907799_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes', models.JSONField(default=list)),
                ('connections', models.JSONField(default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_snapshots', to='inventory_app.agent')),
            ],
            options={
                'db_table': 'process_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['agent', '-captured_at'], name='process_sna_agent_i_c61c82_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='inventory_app.agent')),
            ],
            options={
                'db_table': 'screen_captures',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['agent', '-captured_at'], name='screen_capt_agent_i_a198f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=128)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('install_location', models.CharField(blank=True, default='', max_length=512)),
                ('software_type', models.CharField(db_index=True, default='application', max_length=64)),
                ('size_mb', models.FloatField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='inventory_app.agent')),
            ],
            options={
                'db_table': 'inventory_software',
                'indexes': [models.Index(fields=['agent', 'name'], name='inventory_s_agent_i_1a0482_idx'), models.Index(fields=['name', 'version'], name='inventory_s_name_0b90cf_idx'), models.Index(fields=['software_type'], name='inventory_s_softwar_2fc4f9_idx'), models.Index(fields=['is_system'], name='inventory_s_is_syst_9eda62_idx')],
                'unique_together': {('agent', 'name', 'version', 'publisher')},
            },
        ),
    ]
