# Generated by Django 6.0.7 on 2026-07-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('webhook', 'Webhook')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('severity_filter', models.JSONField(default=list, help_text='List of severities to alert on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bus_alert_channels',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('channel', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='sent', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bus_alert_history',
                'ordering': ['-sent_at'],
            },
        ),
    ]
