# Generated by Django 6.0.5 on 2026-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPENSEARCH_LOGS', '0003_default_retention_policies'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logevent',
            new_name='logs_events_event_t_5a7c5d_idx',
            old_name='logs_events_event_t_2a1f0e_idx',
        ),
        migrations.RenameIndex(
            model_name='logevent',
            new_name='logs_events_event_t_434fbb_idx',
            old_name='logs_events_event_t_5c9a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='logevent',
            new_name='logs_events_host_ip_33439c_idx',
            old_name='logs_events_host_ip_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='logevent',
            new_name='logs_events_severit_ee02df_idx',
            old_name='logs_events_severit_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='logevent',
            new_name='logs_events_event_c_317512_idx',
            old_name='logs_events_event_c_7g8h9i_idx',
        ),
        migrations.AddIndex(
            model_name='logsource',
            index=models.Index(fields=['source_type', 'enabled'], name='logs_source_source__46b49b_idx'),
        ),
        migrations.AddIndex(
            model_name='logsource',
            index=models.Index(fields=['vendor'], name='logs_source_vendor_3a40e1_idx'),
        ),
        migrations.AddIndex(
            model_name='logsource',
            index=models.Index(fields=['host_ip'], name='logs_source_host_ip_427e86_idx'),
        ),
    ]
