# Generated by Django 5.2.3 on 2026-01-02 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EVENT_M", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("anomaly_detection", "Detección de Anomalías"),
                            ("pattern_analysis", "Análisis de Patrones"),
                            ("incident_creation", "Creación de Incidentes"),
                            ("measure_application", "Aplicación de Medidas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("logs_analyzed", models.IntegerField(default=0)),
                ("anomalies_detected", models.IntegerField(default=0)),
                ("incidents_created", models.IntegerField(default=0)),
                ("measures_applied", models.IntegerField(default=0)),
                ("processing_time", models.FloatField(default=0.0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Análisis IA",
                "verbose_name_plural": "Logs de Análisis IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_analysis_enabled", models.BooleanField(default=False)),
                ("analysis_interval_hours", models.IntegerField(default=24)),
                (
                    "anomaly_threshold",
                    models.FloatField(
                        default=0.1,
                        help_text="Umbral para detección de anomalías (0-1)",
                    ),
                ),
                (
                    "min_confidence_score",
                    models.FloatField(
                        default=0.7,
                        help_text="Confianza mínima para crear incidentes (0-1)",
                    ),
                ),
                (
                    "max_incidents_per_hour",
                    models.IntegerField(
                        default=10, help_text="Máximo incidentes por hora"
                    ),
                ),
                (
                    "require_human_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Requiere aprobación humana para medidas críticas",
                    ),
                ),
                (
                    "learning_enabled",
                    models.BooleanField(
                        default=True, help_text="Habilitar aprendizaje continuo"
                    ),
                ),
                (
                    "feedback_retrain_threshold",
                    models.IntegerField(
                        default=10, help_text="Feedback necesario para re-entrenar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración IA",
                "verbose_name_plural": "Configuraciones IA",
            },
        ),
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("anomaly_detector", "Detector de Anomalías"),
                            ("incident_classifier", "Clasificador de Incidentes"),
                            ("pattern_analyzer", "Analizador de Patrones"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("accuracy_score", models.FloatField(default=0.0)),
                ("precision_score", models.FloatField(default=0.0)),
                ("recall_score", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("model_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Modelo IA",
                "verbose_name_plural": "Configuraciones de Modelos IA",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_predictions", models.IntegerField(default=0)),
                ("true_positives", models.IntegerField(default=0)),
                ("false_positives", models.IntegerField(default=0)),
                ("true_negatives", models.IntegerField(default=0)),
                ("false_negatives", models.IntegerField(default=0)),
                ("incidents_created", models.IntegerField(default=0)),
                ("incidents_validated", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("human_feedback_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Métrica de Rendimiento IA",
                "verbose_name_plural": "Métricas de Rendimiento IA",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="HumanFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("false_positive", "Falso Positivo"),
                            ("false_negative", "Falso Negativo"),
                            ("wrong_classification", "Clasificación Incorrecta"),
                            ("good_prediction", "Predicción Correcta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "correct_classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "confidence_level",
                    models.IntegerField(
                        choices=[
                            (1, "1/10"),
                            (2, "2/10"),
                            (3, "3/10"),
                            (4, "4/10"),
                            (5, "5/10"),
                            (6, "6/10"),
                            (7, "7/10"),
                            (8, "8/10"),
                            (9, "9/10"),
                            (10, "10/10"),
                        ],
                        default=5,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EVENT_M.incidente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Humano",
                "verbose_name_plural": "Feedback Humano",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_type", models.CharField(max_length=100)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("Low", "Bajo"),
                            ("Medium", "Medio"),
                            ("High", "Alto"),
                            ("Critical", "Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("involved_ips", models.JSONField(default=list)),
                ("related_logs_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("validated", "Validado"),
                            ("rejected", "Rechazado"),
                            ("auto_created", "Creado Automáticamente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EVENT_M.incidente",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Incidente",
                "verbose_name_plural": "Predicciones de Incidentes",
                "ordering": ["-created_at"],
            },
        ),
    ]
