# Generated by Django 5.2.3 on 2026-01-05 01:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EVENT_M", "0001_initial"),
        ("IRIS", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICircuitBreaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("closed", "Cerrado - Funcionando Normal"),
                            ("open", "Abierto - Bloqueado por Fallos"),
                            ("half_open", "Semi-Abierto - Probando Recuperación"),
                        ],
                        default="closed",
                        max_length=10,
                    ),
                ),
                (
                    "failure_threshold",
                    models.IntegerField(
                        default=5,
                        help_text="Fallos consecutivos para abrir el circuito",
                    ),
                ),
                (
                    "recovery_timeout_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="Tiempo para intentar recuperación (segundos)",
                    ),
                ),
                (
                    "success_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Éxitos consecutivos para cerrar el circuito",
                    ),
                ),
                ("current_failures", models.IntegerField(default=0)),
                ("current_successes", models.IntegerField(default=0)),
                ("last_failure_time", models.DateTimeField(blank=True, null=True)),
                ("last_success_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circuit Breaker IA",
                "verbose_name_plural": "Circuit Breakers IA",
            },
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="adaptive_thresholds",
            field=models.BooleanField(
                default=True,
                help_text="Ajustar umbrales automáticamente basado en rendimiento",
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="adoption_phase",
            field=models.CharField(
                choices=[
                    ("passive", "Pasivo - Solo Predicciones"),
                    ("supervised", "Supervisado - Predicciones con Validación"),
                    (
                        "semi_automated",
                        "Semi-Automático - Incidentes de Alta Confianza",
                    ),
                    ("full_automated", "Totalmente Automático"),
                ],
                default="passive",
                help_text="Fase de adopción del sistema de IA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="alert_email_recipients",
            field=models.JSONField(
                default=list, help_text="Lista de emails para alertas"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="auto_apply_measures",
            field=models.BooleanField(
                default=False, help_text="Aplicar medidas automáticamente"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="auto_create_incidents",
            field=models.BooleanField(
                default=False, help_text="Crear incidentes automáticamente"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="circuit_breaker_enabled",
            field=models.BooleanField(
                default=True, help_text="Habilitar circuit breaker automático"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="circuit_breaker_threshold",
            field=models.FloatField(
                default=0.3,
                help_text="Umbral de falsos positivos para activar circuit breaker (0-1)",
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="correlation_time_window",
            field=models.IntegerField(
                default=30, help_text="Ventana de tiempo para correlación (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_anomaly_alerts",
            field=models.BooleanField(
                default=True, help_text="Alertas de anomalías detectadas"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_deep_learning",
            field=models.BooleanField(
                default=False, help_text="Habilitar modelos de deep learning"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_external_integrations",
            field=models.BooleanField(
                default=False, help_text="Integrar fuentes externas (EDR, firewalls)"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="enable_performance_alerts",
            field=models.BooleanField(
                default=True, help_text="Alertas de rendimiento del sistema"
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="max_predictions_per_hour",
            field=models.IntegerField(
                default=50, help_text="Máximo predicciones por hora"
            ),
        ),
        migrations.CreateModel(
            name="AIAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("performance_degraded", "Rendimiento Degradado"),
                            (
                                "high_false_positive_rate",
                                "Alta Tasa de Falsos Positivos",
                            ),
                            ("model_accuracy_drop", "Caída en Precisión del Modelo"),
                            ("rate_limit_exceeded", "Límite de Tasa Excedido"),
                            ("circuit_breaker_open", "Circuit Breaker Abierto"),
                            ("anomaly_detected", "Anomalía Detectada"),
                            (
                                "incident_auto_created",
                                "Incidente Creado Automáticamente",
                            ),
                            ("system_error", "Error del Sistema"),
                            ("training_completed", "Entrenamiento Completado"),
                            ("configuration_changed", "Configuración Cambiada"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta IA",
                "verbose_name_plural": "Alertas IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("prediction_creation", "Creación de Predicciones"),
                            ("incident_creation", "Creación de Incidentes"),
                            ("measure_application", "Aplicación de Medidas"),
                            ("analysis_execution", "Ejecución de Análisis"),
                        ],
                        max_length=25,
                    ),
                ),
                ("time_window_minutes", models.IntegerField(default=60)),
                ("max_actions", models.IntegerField(default=10)),
                ("current_count", models.IntegerField(default=0)),
                (
                    "window_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("last_blocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Límite de Tasa IA",
                "verbose_name_plural": "Límites de Tasa IA",
                "unique_together": {("action_type", "time_window_minutes")},
            },
        ),
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("prediction_created", "Predicción Creada"),
                            ("prediction_validated", "Predicción Validada"),
                            ("prediction_rejected", "Predicción Rechazada"),
                            (
                                "incident_auto_created",
                                "Incidente Creado Automáticamente",
                            ),
                            ("measure_auto_applied", "Medida Aplicada Automáticamente"),
                            ("analysis_executed", "Análisis Ejecutado"),
                            ("model_trained", "Modelo Entrenado"),
                            ("rate_limit_exceeded", "Límite de Tasa Excedido"),
                            ("circuit_breaker_triggered", "Circuit Breaker Activado"),
                            ("human_feedback_received", "Feedback Humano Recibido"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("critical", "Crítico"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Datos adicionales en formato JSON"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="EVENT_M.incidente",
                    ),
                ),
                (
                    "related_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="IRIS.incidentprediction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoría IA",
                "verbose_name_plural": "Logs de Auditoría IA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="IRIS_aiaudi_action__303d9a_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="IRIS_aiaudi_severit_5e61d7_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="IRIS_aiaudi_user_id_6bb9fd_idx",
                    ),
                ],
            },
        ),
    ]
