# Generated by Django 6.0.5 on 2026-05-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlpPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique policy code', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='high', max_length=16)),
                ('scan_paths', models.JSONField(blank=True, default=list)),
                ('monitored_extensions', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.IntegerField(default=25)),
                ('max_scan_seconds', models.IntegerField(default=20)),
                ('target_os', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DLP Policy',
                'verbose_name_plural': 'DLP Policies',
                'db_table': 'aegis_policies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DlpScanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('agent_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('files_scanned', models.IntegerField(default=0)),
                ('files_flagged', models.IntegerField(default=0)),
                ('incidents_created', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('error', 'Error')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DLP Scan Summary',
                'verbose_name_plural': 'DLP Scan Summaries',
                'db_table': 'aegis_scan_summaries',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DlpThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 dedup key', max_length=128, unique=True)),
                ('agent_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('agent_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('policy_code', models.SlugField(blank=True, default='', max_length=64)),
                ('rule_name', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='high', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=24)),
                ('file_name', models.CharField(blank=True, default='', max_length=512)),
                ('file_path', models.TextField(blank=True, default='')),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(choices=[('filesystem', 'Filesystem'), ('downloads', 'Downloads'), ('desktop', 'Desktop'), ('documents', 'Documents'), ('removable', 'Removable Media'), ('network', 'Network Share'), ('email', 'Email'), ('clipboard', 'Clipboard'), ('usb', 'USB'), ('cloud', 'Cloud Storage'), ('web', 'Web Upload')], default='filesystem', max_length=32)),
                ('summary', models.TextField(blank=True, default='')),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_published', models.BooleanField(default=False, help_text='Published to service bus')),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'DLP Threat',
                'verbose_name_plural': 'DLP Threats',
                'db_table': 'aegis_threats',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['severity', 'status'], name='aegis_threa_severit_4234f6_idx'), models.Index(fields=['classification', 'status'], name='aegis_threa_classif_2f4741_idx'), models.Index(fields=['agent_id', 'detected_at'], name='aegis_threa_agent_i_eb6d8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DlpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pattern', models.TextField(help_text='Keyword or regex pattern to match')),
                ('match_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regular Expression'), ('metadata', 'Metadata')], default='keyword', max_length=16)),
                ('classification', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='high', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='AEGIS.dlppolicy')),
            ],
            options={
                'verbose_name': 'DLP Rule',
                'verbose_name_plural': 'DLP Rules',
                'db_table': 'aegis_rules',
                'ordering': ['policy', 'name'],
                'indexes': [models.Index(fields=['policy', 'is_active'], name='aegis_rules_policy__93764e_idx')],
            },
        ),
    ]
