# Generated by Django 6.0.5 on 2026-05-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEGIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpthreat',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Uploaded copy of the file that triggered the threat', max_length=512, null=True, upload_to='aegis/evidence/%Y/%m/%d/'),
        ),
    ]
